/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechIndexRouteImport } from './routes/tech.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TechScheduleRouteImport } from './routes/tech.schedule'
import { Route as TechRoutePlanRouteImport } from './routes/tech.route-plan'
import { Route as QrElevatorIdRouteImport } from './routes/qr.$elevatorId'
import { Route as PortalIssuesRouteImport } from './routes/portal.issues'
import { Route as PortalContractsRouteImport } from './routes/portal.contracts'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminHrRouteImport } from './routes/admin.hr'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAccountingRouteImport } from './routes/admin.accounting'
import { Route as TechJobsIndexRouteImport } from './routes/tech.jobs.index'
import { Route as PortalElevatorsIndexRouteImport } from './routes/portal.elevators.index'
import { Route as AppTechIndexRouteImport } from './routes/app.tech.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as AdminMaintenanceIndexRouteImport } from './routes/admin.maintenance.index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin.jobs.index'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin.inventory.index'
import { Route as AdminElevatorsIndexRouteImport } from './routes/admin.elevators.index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as TechProjectsProjectIdRouteImport } from './routes/tech.projects.$projectId'
import { Route as TechMaintJobIdRouteImport } from './routes/tech.maint.$jobId'
import { Route as TechJobsJobIdRouteImport } from './routes/tech.jobs.$jobId'
import { Route as PortalElevatorsElevatorIdRouteImport } from './routes/portal.elevators.$elevatorId'
import { Route as AppTechScheduleRouteImport } from './routes/app.tech.schedule'
import { Route as AppTechRoutePlanRouteImport } from './routes/app.tech.route-plan'
import { Route as AppAdminReportsRouteImport } from './routes/app.admin.reports'
import { Route as AppAdminProfileRouteImport } from './routes/app.admin.profile'
import { Route as AppAdminLeadsRouteImport } from './routes/app.admin.leads'
import { Route as AppAdminContractsRouteImport } from './routes/app.admin.contracts'
import { Route as AppAdminApprovalsRouteImport } from './routes/app.admin.approvals'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin.projects.$projectId'
import { Route as AdminJobsJobIdRouteImport } from './routes/admin.jobs.$jobId'
import { Route as AdminElevatorsElevatorIdRouteImport } from './routes/admin.elevators.$elevatorId'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'
import { Route as AppTechJobsIndexRouteImport } from './routes/app.tech.jobs.index'
import { Route as AppAdminProjectsIndexRouteImport } from './routes/app.admin.projects.index'
import { Route as AppAdminJobsIndexRouteImport } from './routes/app.admin.jobs.index'
import { Route as AppAdminElevatorsIndexRouteImport } from './routes/app.admin.elevators.index'
import { Route as TechJobsJobIdMaintenanceRouteImport } from './routes/tech.jobs.$jobId.maintenance'
import { Route as AppTechProjectsProjectIdRouteImport } from './routes/app.tech.projects.$projectId'
import { Route as AppTechMaintJobIdRouteImport } from './routes/app.tech.maint.$jobId'
import { Route as AppTechJobsJobIdRouteImport } from './routes/app.tech.jobs.$jobId'
import { Route as AppAdminProjectsProjectIdRouteImport } from './routes/app.admin.projects.$projectId'
import { Route as AppAdminJobsJobIdRouteImport } from './routes/app.admin.jobs.$jobId'
import { Route as AppAdminElevatorsElevatorIdRouteImport } from './routes/app.admin.elevators.$elevatorId'
import { Route as AdminElevatorsElevatorIdQrRouteImport } from './routes/admin.elevators.$elevatorId.qr'
import { Route as AppTechJobsJobIdMaintenanceRouteImport } from './routes/app.tech.jobs.$jobId.maintenance'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechIndexRoute = TechIndexRouteImport.update({
  id: '/tech/',
  path: '/tech/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechScheduleRoute = TechScheduleRouteImport.update({
  id: '/tech/schedule',
  path: '/tech/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRoutePlanRoute = TechRoutePlanRouteImport.update({
  id: '/tech/route-plan',
  path: '/tech/route-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const QrElevatorIdRoute = QrElevatorIdRouteImport.update({
  id: '/qr/$elevatorId',
  path: '/qr/$elevatorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIssuesRoute = PortalIssuesRouteImport.update({
  id: '/portal/issues',
  path: '/portal/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalContractsRoute = PortalContractsRouteImport.update({
  id: '/portal/contracts',
  path: '/portal/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHrRoute = AdminHrRouteImport.update({
  id: '/admin/hr',
  path: '/admin/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/admin/contracts',
  path: '/admin/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountingRoute = AdminAccountingRouteImport.update({
  id: '/admin/accounting',
  path: '/admin/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const TechJobsIndexRoute = TechJobsIndexRouteImport.update({
  id: '/tech/jobs/',
  path: '/tech/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalElevatorsIndexRoute = PortalElevatorsIndexRouteImport.update({
  id: '/portal/elevators/',
  path: '/portal/elevators/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTechIndexRoute = AppTechIndexRouteImport.update({
  id: '/tech/',
  path: '/tech/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMaintenanceIndexRoute = AdminMaintenanceIndexRouteImport.update({
  id: '/admin/maintenance/',
  path: '/admin/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminJobsRoute,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/admin/inventory/',
  path: '/admin/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminElevatorsIndexRoute = AdminElevatorsIndexRouteImport.update({
  id: '/admin/elevators/',
  path: '/admin/elevators/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/admin/customers/',
  path: '/admin/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechProjectsProjectIdRoute = TechProjectsProjectIdRouteImport.update({
  id: '/tech/projects/$projectId',
  path: '/tech/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const TechMaintJobIdRoute = TechMaintJobIdRouteImport.update({
  id: '/tech/maint/$jobId',
  path: '/tech/maint/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const TechJobsJobIdRoute = TechJobsJobIdRouteImport.update({
  id: '/tech/jobs/$jobId',
  path: '/tech/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalElevatorsElevatorIdRoute =
  PortalElevatorsElevatorIdRouteImport.update({
    id: '/portal/elevators/$elevatorId',
    path: '/portal/elevators/$elevatorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppTechScheduleRoute = AppTechScheduleRouteImport.update({
  id: '/tech/schedule',
  path: '/tech/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppTechRoutePlanRoute = AppTechRoutePlanRouteImport.update({
  id: '/tech/route-plan',
  path: '/tech/route-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProfileRoute = AppAdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLeadsRoute = AppAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminContractsRoute = AppAdminContractsRouteImport.update({
  id: '/admin/contracts',
  path: '/admin/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApprovalsRoute = AppAdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/admin/projects/$projectId',
  path: '/admin/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsJobIdRoute = AdminJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AdminJobsRoute,
} as any)
const AdminElevatorsElevatorIdRoute =
  AdminElevatorsElevatorIdRouteImport.update({
    id: '/admin/elevators/$elevatorId',
    path: '/admin/elevators/$elevatorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/admin/customers/$customerId',
    path: '/admin/customers/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppTechJobsIndexRoute = AppTechJobsIndexRouteImport.update({
  id: '/tech/jobs/',
  path: '/tech/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProjectsIndexRoute = AppAdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminJobsIndexRoute = AppAdminJobsIndexRouteImport.update({
  id: '/admin/jobs/',
  path: '/admin/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminElevatorsIndexRoute = AppAdminElevatorsIndexRouteImport.update({
  id: '/admin/elevators/',
  path: '/admin/elevators/',
  getParentRoute: () => AppRoute,
} as any)
const TechJobsJobIdMaintenanceRoute =
  TechJobsJobIdMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => TechJobsJobIdRoute,
  } as any)
const AppTechProjectsProjectIdRoute =
  AppTechProjectsProjectIdRouteImport.update({
    id: '/tech/projects/$projectId',
    path: '/tech/projects/$projectId',
    getParentRoute: () => AppRoute,
  } as any)
const AppTechMaintJobIdRoute = AppTechMaintJobIdRouteImport.update({
  id: '/tech/maint/$jobId',
  path: '/tech/maint/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppTechJobsJobIdRoute = AppTechJobsJobIdRouteImport.update({
  id: '/tech/jobs/$jobId',
  path: '/tech/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProjectsProjectIdRoute =
  AppAdminProjectsProjectIdRouteImport.update({
    id: '/admin/projects/$projectId',
    path: '/admin/projects/$projectId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminJobsJobIdRoute = AppAdminJobsJobIdRouteImport.update({
  id: '/admin/jobs/$jobId',
  path: '/admin/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminElevatorsElevatorIdRoute =
  AppAdminElevatorsElevatorIdRouteImport.update({
    id: '/admin/elevators/$elevatorId',
    path: '/admin/elevators/$elevatorId',
    getParentRoute: () => AppRoute,
  } as any)
const AdminElevatorsElevatorIdQrRoute =
  AdminElevatorsElevatorIdQrRouteImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AdminElevatorsElevatorIdRoute,
  } as any)
const AppTechJobsJobIdMaintenanceRoute =
  AppTechJobsJobIdMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AppTechJobsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/issues': typeof PortalIssuesRoute
  '/qr/$elevatorId': typeof QrElevatorIdRoute
  '/tech/route-plan': typeof TechRoutePlanRoute
  '/tech/schedule': typeof TechScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/tech/': typeof TechIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/elevators/$elevatorId': typeof AdminElevatorsElevatorIdRouteWithChildren
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/app/admin/approvals': typeof AppAdminApprovalsRoute
  '/app/admin/contracts': typeof AppAdminContractsRoute
  '/app/admin/leads': typeof AppAdminLeadsRoute
  '/app/admin/profile': typeof AppAdminProfileRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/tech/route-plan': typeof AppTechRoutePlanRoute
  '/app/tech/schedule': typeof AppTechScheduleRoute
  '/portal/elevators/$elevatorId': typeof PortalElevatorsElevatorIdRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRouteWithChildren
  '/tech/maint/$jobId': typeof TechMaintJobIdRoute
  '/tech/projects/$projectId': typeof TechProjectsProjectIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/elevators/': typeof AdminElevatorsIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/maintenance/': typeof AdminMaintenanceIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/tech/': typeof AppTechIndexRoute
  '/portal/elevators/': typeof PortalElevatorsIndexRoute
  '/tech/jobs/': typeof TechJobsIndexRoute
  '/admin/elevators/$elevatorId/qr': typeof AdminElevatorsElevatorIdQrRoute
  '/app/admin/elevators/$elevatorId': typeof AppAdminElevatorsElevatorIdRoute
  '/app/admin/jobs/$jobId': typeof AppAdminJobsJobIdRoute
  '/app/admin/projects/$projectId': typeof AppAdminProjectsProjectIdRoute
  '/app/tech/jobs/$jobId': typeof AppTechJobsJobIdRouteWithChildren
  '/app/tech/maint/$jobId': typeof AppTechMaintJobIdRoute
  '/app/tech/projects/$projectId': typeof AppTechProjectsProjectIdRoute
  '/tech/jobs/$jobId/maintenance': typeof TechJobsJobIdMaintenanceRoute
  '/app/admin/elevators/': typeof AppAdminElevatorsIndexRoute
  '/app/admin/jobs/': typeof AppAdminJobsIndexRoute
  '/app/admin/projects/': typeof AppAdminProjectsIndexRoute
  '/app/tech/jobs/': typeof AppTechJobsIndexRoute
  '/app/tech/jobs/$jobId/maintenance': typeof AppTechJobsJobIdMaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/issues': typeof PortalIssuesRoute
  '/qr/$elevatorId': typeof QrElevatorIdRoute
  '/tech/route-plan': typeof TechRoutePlanRoute
  '/tech/schedule': typeof TechScheduleRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/tech': typeof TechIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/elevators/$elevatorId': typeof AdminElevatorsElevatorIdRouteWithChildren
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/app/admin/approvals': typeof AppAdminApprovalsRoute
  '/app/admin/contracts': typeof AppAdminContractsRoute
  '/app/admin/leads': typeof AppAdminLeadsRoute
  '/app/admin/profile': typeof AppAdminProfileRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/tech/route-plan': typeof AppTechRoutePlanRoute
  '/app/tech/schedule': typeof AppTechScheduleRoute
  '/portal/elevators/$elevatorId': typeof PortalElevatorsElevatorIdRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRouteWithChildren
  '/tech/maint/$jobId': typeof TechMaintJobIdRoute
  '/tech/projects/$projectId': typeof TechProjectsProjectIdRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/elevators': typeof AdminElevatorsIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/maintenance': typeof AdminMaintenanceIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/tech': typeof AppTechIndexRoute
  '/portal/elevators': typeof PortalElevatorsIndexRoute
  '/tech/jobs': typeof TechJobsIndexRoute
  '/admin/elevators/$elevatorId/qr': typeof AdminElevatorsElevatorIdQrRoute
  '/app/admin/elevators/$elevatorId': typeof AppAdminElevatorsElevatorIdRoute
  '/app/admin/jobs/$jobId': typeof AppAdminJobsJobIdRoute
  '/app/admin/projects/$projectId': typeof AppAdminProjectsProjectIdRoute
  '/app/tech/jobs/$jobId': typeof AppTechJobsJobIdRouteWithChildren
  '/app/tech/maint/$jobId': typeof AppTechMaintJobIdRoute
  '/app/tech/projects/$projectId': typeof AppTechProjectsProjectIdRoute
  '/tech/jobs/$jobId/maintenance': typeof TechJobsJobIdMaintenanceRoute
  '/app/admin/elevators': typeof AppAdminElevatorsIndexRoute
  '/app/admin/jobs': typeof AppAdminJobsIndexRoute
  '/app/admin/projects': typeof AppAdminProjectsIndexRoute
  '/app/tech/jobs': typeof AppTechJobsIndexRoute
  '/app/tech/jobs/$jobId/maintenance': typeof AppTechJobsJobIdMaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/issues': typeof PortalIssuesRoute
  '/qr/$elevatorId': typeof QrElevatorIdRoute
  '/tech/route-plan': typeof TechRoutePlanRoute
  '/tech/schedule': typeof TechScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/tech/': typeof TechIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/elevators/$elevatorId': typeof AdminElevatorsElevatorIdRouteWithChildren
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/app/admin/approvals': typeof AppAdminApprovalsRoute
  '/app/admin/contracts': typeof AppAdminContractsRoute
  '/app/admin/leads': typeof AppAdminLeadsRoute
  '/app/admin/profile': typeof AppAdminProfileRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/tech/route-plan': typeof AppTechRoutePlanRoute
  '/app/tech/schedule': typeof AppTechScheduleRoute
  '/portal/elevators/$elevatorId': typeof PortalElevatorsElevatorIdRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRouteWithChildren
  '/tech/maint/$jobId': typeof TechMaintJobIdRoute
  '/tech/projects/$projectId': typeof TechProjectsProjectIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/elevators/': typeof AdminElevatorsIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/maintenance/': typeof AdminMaintenanceIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/tech/': typeof AppTechIndexRoute
  '/portal/elevators/': typeof PortalElevatorsIndexRoute
  '/tech/jobs/': typeof TechJobsIndexRoute
  '/admin/elevators/$elevatorId/qr': typeof AdminElevatorsElevatorIdQrRoute
  '/app/admin/elevators/$elevatorId': typeof AppAdminElevatorsElevatorIdRoute
  '/app/admin/jobs/$jobId': typeof AppAdminJobsJobIdRoute
  '/app/admin/projects/$projectId': typeof AppAdminProjectsProjectIdRoute
  '/app/tech/jobs/$jobId': typeof AppTechJobsJobIdRouteWithChildren
  '/app/tech/maint/$jobId': typeof AppTechMaintJobIdRoute
  '/app/tech/projects/$projectId': typeof AppTechProjectsProjectIdRoute
  '/tech/jobs/$jobId/maintenance': typeof TechJobsJobIdMaintenanceRoute
  '/app/admin/elevators/': typeof AppAdminElevatorsIndexRoute
  '/app/admin/jobs/': typeof AppAdminJobsIndexRoute
  '/app/admin/projects/': typeof AppAdminProjectsIndexRoute
  '/app/tech/jobs/': typeof AppTechJobsIndexRoute
  '/app/tech/jobs/$jobId/maintenance': typeof AppTechJobsJobIdMaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/admin/accounting'
    | '/admin/approvals'
    | '/admin/contracts'
    | '/admin/hr'
    | '/admin/jobs'
    | '/admin/leads'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/portal/contracts'
    | '/portal/issues'
    | '/qr/$elevatorId'
    | '/tech/route-plan'
    | '/tech/schedule'
    | '/admin/'
    | '/portal/'
    | '/tech/'
    | '/admin/customers/$customerId'
    | '/admin/elevators/$elevatorId'
    | '/admin/jobs/$jobId'
    | '/admin/projects/$projectId'
    | '/app/admin/approvals'
    | '/app/admin/contracts'
    | '/app/admin/leads'
    | '/app/admin/profile'
    | '/app/admin/reports'
    | '/app/tech/route-plan'
    | '/app/tech/schedule'
    | '/portal/elevators/$elevatorId'
    | '/tech/jobs/$jobId'
    | '/tech/maint/$jobId'
    | '/tech/projects/$projectId'
    | '/admin/customers/'
    | '/admin/elevators/'
    | '/admin/inventory/'
    | '/admin/jobs/'
    | '/admin/maintenance/'
    | '/admin/projects/'
    | '/app/admin/'
    | '/app/tech/'
    | '/portal/elevators/'
    | '/tech/jobs/'
    | '/admin/elevators/$elevatorId/qr'
    | '/app/admin/elevators/$elevatorId'
    | '/app/admin/jobs/$jobId'
    | '/app/admin/projects/$projectId'
    | '/app/tech/jobs/$jobId'
    | '/app/tech/maint/$jobId'
    | '/app/tech/projects/$projectId'
    | '/tech/jobs/$jobId/maintenance'
    | '/app/admin/elevators/'
    | '/app/admin/jobs/'
    | '/app/admin/projects/'
    | '/app/tech/jobs/'
    | '/app/tech/jobs/$jobId/maintenance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/admin/accounting'
    | '/admin/approvals'
    | '/admin/contracts'
    | '/admin/hr'
    | '/admin/leads'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/portal/contracts'
    | '/portal/issues'
    | '/qr/$elevatorId'
    | '/tech/route-plan'
    | '/tech/schedule'
    | '/admin'
    | '/portal'
    | '/tech'
    | '/admin/customers/$customerId'
    | '/admin/elevators/$elevatorId'
    | '/admin/jobs/$jobId'
    | '/admin/projects/$projectId'
    | '/app/admin/approvals'
    | '/app/admin/contracts'
    | '/app/admin/leads'
    | '/app/admin/profile'
    | '/app/admin/reports'
    | '/app/tech/route-plan'
    | '/app/tech/schedule'
    | '/portal/elevators/$elevatorId'
    | '/tech/jobs/$jobId'
    | '/tech/maint/$jobId'
    | '/tech/projects/$projectId'
    | '/admin/customers'
    | '/admin/elevators'
    | '/admin/inventory'
    | '/admin/jobs'
    | '/admin/maintenance'
    | '/admin/projects'
    | '/app/admin'
    | '/app/tech'
    | '/portal/elevators'
    | '/tech/jobs'
    | '/admin/elevators/$elevatorId/qr'
    | '/app/admin/elevators/$elevatorId'
    | '/app/admin/jobs/$jobId'
    | '/app/admin/projects/$projectId'
    | '/app/tech/jobs/$jobId'
    | '/app/tech/maint/$jobId'
    | '/app/tech/projects/$projectId'
    | '/tech/jobs/$jobId/maintenance'
    | '/app/admin/elevators'
    | '/app/admin/jobs'
    | '/app/admin/projects'
    | '/app/tech/jobs'
    | '/app/tech/jobs/$jobId/maintenance'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/admin/accounting'
    | '/admin/approvals'
    | '/admin/contracts'
    | '/admin/hr'
    | '/admin/jobs'
    | '/admin/leads'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/portal/contracts'
    | '/portal/issues'
    | '/qr/$elevatorId'
    | '/tech/route-plan'
    | '/tech/schedule'
    | '/admin/'
    | '/portal/'
    | '/tech/'
    | '/admin/customers/$customerId'
    | '/admin/elevators/$elevatorId'
    | '/admin/jobs/$jobId'
    | '/admin/projects/$projectId'
    | '/app/admin/approvals'
    | '/app/admin/contracts'
    | '/app/admin/leads'
    | '/app/admin/profile'
    | '/app/admin/reports'
    | '/app/tech/route-plan'
    | '/app/tech/schedule'
    | '/portal/elevators/$elevatorId'
    | '/tech/jobs/$jobId'
    | '/tech/maint/$jobId'
    | '/tech/projects/$projectId'
    | '/admin/customers/'
    | '/admin/elevators/'
    | '/admin/inventory/'
    | '/admin/jobs/'
    | '/admin/maintenance/'
    | '/admin/projects/'
    | '/app/admin/'
    | '/app/tech/'
    | '/portal/elevators/'
    | '/tech/jobs/'
    | '/admin/elevators/$elevatorId/qr'
    | '/app/admin/elevators/$elevatorId'
    | '/app/admin/jobs/$jobId'
    | '/app/admin/projects/$projectId'
    | '/app/tech/jobs/$jobId'
    | '/app/tech/maint/$jobId'
    | '/app/tech/projects/$projectId'
    | '/tech/jobs/$jobId/maintenance'
    | '/app/admin/elevators/'
    | '/app/admin/jobs/'
    | '/app/admin/projects/'
    | '/app/tech/jobs/'
    | '/app/tech/jobs/$jobId/maintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminAccountingRoute: typeof AdminAccountingRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminHrRoute: typeof AdminHrRoute
  AdminJobsRoute: typeof AdminJobsRouteWithChildren
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  PortalContractsRoute: typeof PortalContractsRoute
  PortalIssuesRoute: typeof PortalIssuesRoute
  QrElevatorIdRoute: typeof QrElevatorIdRoute
  TechRoutePlanRoute: typeof TechRoutePlanRoute
  TechScheduleRoute: typeof TechScheduleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  TechIndexRoute: typeof TechIndexRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminElevatorsElevatorIdRoute: typeof AdminElevatorsElevatorIdRouteWithChildren
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRoute
  PortalElevatorsElevatorIdRoute: typeof PortalElevatorsElevatorIdRoute
  TechJobsJobIdRoute: typeof TechJobsJobIdRouteWithChildren
  TechMaintJobIdRoute: typeof TechMaintJobIdRoute
  TechProjectsProjectIdRoute: typeof TechProjectsProjectIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminElevatorsIndexRoute: typeof AdminElevatorsIndexRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminMaintenanceIndexRoute: typeof AdminMaintenanceIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  PortalElevatorsIndexRoute: typeof PortalElevatorsIndexRoute
  TechJobsIndexRoute: typeof TechJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/': {
      id: '/tech/'
      path: '/tech'
      fullPath: '/tech/'
      preLoaderRoute: typeof TechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/schedule': {
      id: '/tech/schedule'
      path: '/tech/schedule'
      fullPath: '/tech/schedule'
      preLoaderRoute: typeof TechScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/route-plan': {
      id: '/tech/route-plan'
      path: '/tech/route-plan'
      fullPath: '/tech/route-plan'
      preLoaderRoute: typeof TechRoutePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$elevatorId': {
      id: '/qr/$elevatorId'
      path: '/qr/$elevatorId'
      fullPath: '/qr/$elevatorId'
      preLoaderRoute: typeof QrElevatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/issues': {
      id: '/portal/issues'
      path: '/portal/issues'
      fullPath: '/portal/issues'
      preLoaderRoute: typeof PortalIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/contracts': {
      id: '/portal/contracts'
      path: '/portal/contracts'
      fullPath: '/portal/contracts'
      preLoaderRoute: typeof PortalContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hr': {
      id: '/admin/hr'
      path: '/admin/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AdminHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/admin/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounting': {
      id: '/admin/accounting'
      path: '/admin/accounting'
      fullPath: '/admin/accounting'
      preLoaderRoute: typeof AdminAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/jobs/': {
      id: '/tech/jobs/'
      path: '/tech/jobs'
      fullPath: '/tech/jobs/'
      preLoaderRoute: typeof TechJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/elevators/': {
      id: '/portal/elevators/'
      path: '/portal/elevators'
      fullPath: '/portal/elevators/'
      preLoaderRoute: typeof PortalElevatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tech/': {
      id: '/app/tech/'
      path: '/tech'
      fullPath: '/app/tech/'
      preLoaderRoute: typeof AppTechIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/maintenance/': {
      id: '/admin/maintenance/'
      path: '/admin/maintenance'
      fullPath: '/admin/maintenance/'
      preLoaderRoute: typeof AdminMaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminJobsRoute
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/admin/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/elevators/': {
      id: '/admin/elevators/'
      path: '/admin/elevators'
      fullPath: '/admin/elevators/'
      preLoaderRoute: typeof AdminElevatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/projects/$projectId': {
      id: '/tech/projects/$projectId'
      path: '/tech/projects/$projectId'
      fullPath: '/tech/projects/$projectId'
      preLoaderRoute: typeof TechProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/maint/$jobId': {
      id: '/tech/maint/$jobId'
      path: '/tech/maint/$jobId'
      fullPath: '/tech/maint/$jobId'
      preLoaderRoute: typeof TechMaintJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/jobs/$jobId': {
      id: '/tech/jobs/$jobId'
      path: '/tech/jobs/$jobId'
      fullPath: '/tech/jobs/$jobId'
      preLoaderRoute: typeof TechJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/elevators/$elevatorId': {
      id: '/portal/elevators/$elevatorId'
      path: '/portal/elevators/$elevatorId'
      fullPath: '/portal/elevators/$elevatorId'
      preLoaderRoute: typeof PortalElevatorsElevatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tech/schedule': {
      id: '/app/tech/schedule'
      path: '/tech/schedule'
      fullPath: '/app/tech/schedule'
      preLoaderRoute: typeof AppTechScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tech/route-plan': {
      id: '/app/tech/route-plan'
      path: '/tech/route-plan'
      fullPath: '/app/tech/route-plan'
      preLoaderRoute: typeof AppTechRoutePlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/reports': {
      id: '/app/admin/reports'
      path: '/admin/reports'
      fullPath: '/app/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/profile': {
      id: '/app/admin/profile'
      path: '/admin/profile'
      fullPath: '/app/admin/profile'
      preLoaderRoute: typeof AppAdminProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/leads': {
      id: '/app/admin/leads'
      path: '/admin/leads'
      fullPath: '/app/admin/leads'
      preLoaderRoute: typeof AppAdminLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/contracts': {
      id: '/app/admin/contracts'
      path: '/admin/contracts'
      fullPath: '/app/admin/contracts'
      preLoaderRoute: typeof AppAdminContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/approvals': {
      id: '/app/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/app/admin/approvals'
      preLoaderRoute: typeof AppAdminApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/admin/projects/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/$jobId': {
      id: '/admin/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/admin/jobs/$jobId'
      preLoaderRoute: typeof AdminJobsJobIdRouteImport
      parentRoute: typeof AdminJobsRoute
    }
    '/admin/elevators/$elevatorId': {
      id: '/admin/elevators/$elevatorId'
      path: '/admin/elevators/$elevatorId'
      fullPath: '/admin/elevators/$elevatorId'
      preLoaderRoute: typeof AdminElevatorsElevatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/admin/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tech/jobs/': {
      id: '/app/tech/jobs/'
      path: '/tech/jobs'
      fullPath: '/app/tech/jobs/'
      preLoaderRoute: typeof AppTechJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/projects/': {
      id: '/app/admin/projects/'
      path: '/admin/projects'
      fullPath: '/app/admin/projects/'
      preLoaderRoute: typeof AppAdminProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/jobs/': {
      id: '/app/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/app/admin/jobs/'
      preLoaderRoute: typeof AppAdminJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/elevators/': {
      id: '/app/admin/elevators/'
      path: '/admin/elevators'
      fullPath: '/app/admin/elevators/'
      preLoaderRoute: typeof AppAdminElevatorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/tech/jobs/$jobId/maintenance': {
      id: '/tech/jobs/$jobId/maintenance'
      path: '/maintenance'
      fullPath: '/tech/jobs/$jobId/maintenance'
      preLoaderRoute: typeof TechJobsJobIdMaintenanceRouteImport
      parentRoute: typeof TechJobsJobIdRoute
    }
    '/app/tech/projects/$projectId': {
      id: '/app/tech/projects/$projectId'
      path: '/tech/projects/$projectId'
      fullPath: '/app/tech/projects/$projectId'
      preLoaderRoute: typeof AppTechProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tech/maint/$jobId': {
      id: '/app/tech/maint/$jobId'
      path: '/tech/maint/$jobId'
      fullPath: '/app/tech/maint/$jobId'
      preLoaderRoute: typeof AppTechMaintJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tech/jobs/$jobId': {
      id: '/app/tech/jobs/$jobId'
      path: '/tech/jobs/$jobId'
      fullPath: '/app/tech/jobs/$jobId'
      preLoaderRoute: typeof AppTechJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/projects/$projectId': {
      id: '/app/admin/projects/$projectId'
      path: '/admin/projects/$projectId'
      fullPath: '/app/admin/projects/$projectId'
      preLoaderRoute: typeof AppAdminProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/jobs/$jobId': {
      id: '/app/admin/jobs/$jobId'
      path: '/admin/jobs/$jobId'
      fullPath: '/app/admin/jobs/$jobId'
      preLoaderRoute: typeof AppAdminJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/elevators/$elevatorId': {
      id: '/app/admin/elevators/$elevatorId'
      path: '/admin/elevators/$elevatorId'
      fullPath: '/app/admin/elevators/$elevatorId'
      preLoaderRoute: typeof AppAdminElevatorsElevatorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/elevators/$elevatorId/qr': {
      id: '/admin/elevators/$elevatorId/qr'
      path: '/qr'
      fullPath: '/admin/elevators/$elevatorId/qr'
      preLoaderRoute: typeof AdminElevatorsElevatorIdQrRouteImport
      parentRoute: typeof AdminElevatorsElevatorIdRoute
    }
    '/app/tech/jobs/$jobId/maintenance': {
      id: '/app/tech/jobs/$jobId/maintenance'
      path: '/maintenance'
      fullPath: '/app/tech/jobs/$jobId/maintenance'
      preLoaderRoute: typeof AppTechJobsJobIdMaintenanceRouteImport
      parentRoute: typeof AppTechJobsJobIdRoute
    }
  }
}

interface AppTechJobsJobIdRouteChildren {
  AppTechJobsJobIdMaintenanceRoute: typeof AppTechJobsJobIdMaintenanceRoute
}

const AppTechJobsJobIdRouteChildren: AppTechJobsJobIdRouteChildren = {
  AppTechJobsJobIdMaintenanceRoute: AppTechJobsJobIdMaintenanceRoute,
}

const AppTechJobsJobIdRouteWithChildren =
  AppTechJobsJobIdRoute._addFileChildren(AppTechJobsJobIdRouteChildren)

interface AppRouteChildren {
  AppAdminApprovalsRoute: typeof AppAdminApprovalsRoute
  AppAdminContractsRoute: typeof AppAdminContractsRoute
  AppAdminLeadsRoute: typeof AppAdminLeadsRoute
  AppAdminProfileRoute: typeof AppAdminProfileRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppTechRoutePlanRoute: typeof AppTechRoutePlanRoute
  AppTechScheduleRoute: typeof AppTechScheduleRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppTechIndexRoute: typeof AppTechIndexRoute
  AppAdminElevatorsElevatorIdRoute: typeof AppAdminElevatorsElevatorIdRoute
  AppAdminJobsJobIdRoute: typeof AppAdminJobsJobIdRoute
  AppAdminProjectsProjectIdRoute: typeof AppAdminProjectsProjectIdRoute
  AppTechJobsJobIdRoute: typeof AppTechJobsJobIdRouteWithChildren
  AppTechMaintJobIdRoute: typeof AppTechMaintJobIdRoute
  AppTechProjectsProjectIdRoute: typeof AppTechProjectsProjectIdRoute
  AppAdminElevatorsIndexRoute: typeof AppAdminElevatorsIndexRoute
  AppAdminJobsIndexRoute: typeof AppAdminJobsIndexRoute
  AppAdminProjectsIndexRoute: typeof AppAdminProjectsIndexRoute
  AppTechJobsIndexRoute: typeof AppTechJobsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminApprovalsRoute: AppAdminApprovalsRoute,
  AppAdminContractsRoute: AppAdminContractsRoute,
  AppAdminLeadsRoute: AppAdminLeadsRoute,
  AppAdminProfileRoute: AppAdminProfileRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppTechRoutePlanRoute: AppTechRoutePlanRoute,
  AppTechScheduleRoute: AppTechScheduleRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppTechIndexRoute: AppTechIndexRoute,
  AppAdminElevatorsElevatorIdRoute: AppAdminElevatorsElevatorIdRoute,
  AppAdminJobsJobIdRoute: AppAdminJobsJobIdRoute,
  AppAdminProjectsProjectIdRoute: AppAdminProjectsProjectIdRoute,
  AppTechJobsJobIdRoute: AppTechJobsJobIdRouteWithChildren,
  AppTechMaintJobIdRoute: AppTechMaintJobIdRoute,
  AppTechProjectsProjectIdRoute: AppTechProjectsProjectIdRoute,
  AppAdminElevatorsIndexRoute: AppAdminElevatorsIndexRoute,
  AppAdminJobsIndexRoute: AppAdminJobsIndexRoute,
  AppAdminProjectsIndexRoute: AppAdminProjectsIndexRoute,
  AppTechJobsIndexRoute: AppTechJobsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminJobsRouteChildren {
  AdminJobsJobIdRoute: typeof AdminJobsJobIdRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
}

const AdminJobsRouteChildren: AdminJobsRouteChildren = {
  AdminJobsJobIdRoute: AdminJobsJobIdRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
}

const AdminJobsRouteWithChildren = AdminJobsRoute._addFileChildren(
  AdminJobsRouteChildren,
)

interface AdminElevatorsElevatorIdRouteChildren {
  AdminElevatorsElevatorIdQrRoute: typeof AdminElevatorsElevatorIdQrRoute
}

const AdminElevatorsElevatorIdRouteChildren: AdminElevatorsElevatorIdRouteChildren =
  {
    AdminElevatorsElevatorIdQrRoute: AdminElevatorsElevatorIdQrRoute,
  }

const AdminElevatorsElevatorIdRouteWithChildren =
  AdminElevatorsElevatorIdRoute._addFileChildren(
    AdminElevatorsElevatorIdRouteChildren,
  )

interface TechJobsJobIdRouteChildren {
  TechJobsJobIdMaintenanceRoute: typeof TechJobsJobIdMaintenanceRoute
}

const TechJobsJobIdRouteChildren: TechJobsJobIdRouteChildren = {
  TechJobsJobIdMaintenanceRoute: TechJobsJobIdMaintenanceRoute,
}

const TechJobsJobIdRouteWithChildren = TechJobsJobIdRoute._addFileChildren(
  TechJobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminAccountingRoute: AdminAccountingRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminHrRoute: AdminHrRoute,
  AdminJobsRoute: AdminJobsRouteWithChildren,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  PortalContractsRoute: PortalContractsRoute,
  PortalIssuesRoute: PortalIssuesRoute,
  QrElevatorIdRoute: QrElevatorIdRoute,
  TechRoutePlanRoute: TechRoutePlanRoute,
  TechScheduleRoute: TechScheduleRoute,
  AdminIndexRoute: AdminIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  TechIndexRoute: TechIndexRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminElevatorsElevatorIdRoute: AdminElevatorsElevatorIdRouteWithChildren,
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRoute,
  PortalElevatorsElevatorIdRoute: PortalElevatorsElevatorIdRoute,
  TechJobsJobIdRoute: TechJobsJobIdRouteWithChildren,
  TechMaintJobIdRoute: TechMaintJobIdRoute,
  TechProjectsProjectIdRoute: TechProjectsProjectIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminElevatorsIndexRoute: AdminElevatorsIndexRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminMaintenanceIndexRoute: AdminMaintenanceIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  PortalElevatorsIndexRoute: PortalElevatorsIndexRoute,
  TechJobsIndexRoute: TechJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
