/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechIndexRouteImport } from './routes/tech.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TechScheduleRouteImport } from './routes/tech.schedule'
import { Route as TechRoutePlanRouteImport } from './routes/tech.route-plan'
import { Route as QrElevatorIdRouteImport } from './routes/qr.$elevatorId'
import { Route as PortalIssuesRouteImport } from './routes/portal.issues'
import { Route as PortalContractsRouteImport } from './routes/portal.contracts'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as TechJobsIndexRouteImport } from './routes/tech.jobs.index'
import { Route as PortalElevatorsIndexRouteImport } from './routes/portal.elevators.index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin.jobs.index'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin.inventory.index'
import { Route as AdminElevatorsIndexRouteImport } from './routes/admin.elevators.index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as TechJobsJobIdRouteImport } from './routes/tech.jobs.$jobId'
import { Route as PortalElevatorsElevatorIdRouteImport } from './routes/portal.elevators.$elevatorId'
import { Route as AdminJobsJobIdRouteImport } from './routes/admin.jobs.$jobId'
import { Route as AdminElevatorsElevatorIdRouteImport } from './routes/admin.elevators.$elevatorId'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'
import { Route as AdminElevatorsElevatorIdQrRouteImport } from './routes/admin.elevators.$elevatorId.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechIndexRoute = TechIndexRouteImport.update({
  id: '/tech/',
  path: '/tech/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechScheduleRoute = TechScheduleRouteImport.update({
  id: '/tech/schedule',
  path: '/tech/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRoutePlanRoute = TechRoutePlanRouteImport.update({
  id: '/tech/route-plan',
  path: '/tech/route-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const QrElevatorIdRoute = QrElevatorIdRouteImport.update({
  id: '/qr/$elevatorId',
  path: '/qr/$elevatorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIssuesRoute = PortalIssuesRouteImport.update({
  id: '/portal/issues',
  path: '/portal/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalContractsRoute = PortalContractsRouteImport.update({
  id: '/portal/contracts',
  path: '/portal/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/admin/contracts',
  path: '/admin/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const TechJobsIndexRoute = TechJobsIndexRouteImport.update({
  id: '/tech/jobs/',
  path: '/tech/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalElevatorsIndexRoute = PortalElevatorsIndexRouteImport.update({
  id: '/portal/elevators/',
  path: '/portal/elevators/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/admin/jobs/',
  path: '/admin/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/admin/inventory/',
  path: '/admin/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminElevatorsIndexRoute = AdminElevatorsIndexRouteImport.update({
  id: '/admin/elevators/',
  path: '/admin/elevators/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/admin/customers/',
  path: '/admin/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechJobsJobIdRoute = TechJobsJobIdRouteImport.update({
  id: '/tech/jobs/$jobId',
  path: '/tech/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalElevatorsElevatorIdRoute =
  PortalElevatorsElevatorIdRouteImport.update({
    id: '/portal/elevators/$elevatorId',
    path: '/portal/elevators/$elevatorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminJobsJobIdRoute = AdminJobsJobIdRouteImport.update({
  id: '/admin/jobs/$jobId',
  path: '/admin/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminElevatorsElevatorIdRoute =
  AdminElevatorsElevatorIdRouteImport.update({
    id: '/admin/elevators/$elevatorId',
    path: '/admin/elevators/$elevatorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/admin/customers/$customerId',
    path: '/admin/customers/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminElevatorsElevatorIdQrRoute =
  AdminElevatorsElevatorIdQrRouteImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AdminElevatorsElevatorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/issues': typeof PortalIssuesRoute
  '/qr/$elevatorId': typeof QrElevatorIdRoute
  '/tech/route-plan': typeof TechRoutePlanRoute
  '/tech/schedule': typeof TechScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/tech/': typeof TechIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/elevators/$elevatorId': typeof AdminElevatorsElevatorIdRouteWithChildren
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/portal/elevators/$elevatorId': typeof PortalElevatorsElevatorIdRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/elevators/': typeof AdminElevatorsIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/portal/elevators/': typeof PortalElevatorsIndexRoute
  '/tech/jobs/': typeof TechJobsIndexRoute
  '/admin/elevators/$elevatorId/qr': typeof AdminElevatorsElevatorIdQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/issues': typeof PortalIssuesRoute
  '/qr/$elevatorId': typeof QrElevatorIdRoute
  '/tech/route-plan': typeof TechRoutePlanRoute
  '/tech/schedule': typeof TechScheduleRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/tech': typeof TechIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/elevators/$elevatorId': typeof AdminElevatorsElevatorIdRouteWithChildren
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/portal/elevators/$elevatorId': typeof PortalElevatorsElevatorIdRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/elevators': typeof AdminElevatorsIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/portal/elevators': typeof PortalElevatorsIndexRoute
  '/tech/jobs': typeof TechJobsIndexRoute
  '/admin/elevators/$elevatorId/qr': typeof AdminElevatorsElevatorIdQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/issues': typeof PortalIssuesRoute
  '/qr/$elevatorId': typeof QrElevatorIdRoute
  '/tech/route-plan': typeof TechRoutePlanRoute
  '/tech/schedule': typeof TechScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/tech/': typeof TechIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/elevators/$elevatorId': typeof AdminElevatorsElevatorIdRouteWithChildren
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/portal/elevators/$elevatorId': typeof PortalElevatorsElevatorIdRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/elevators/': typeof AdminElevatorsIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/portal/elevators/': typeof PortalElevatorsIndexRoute
  '/tech/jobs/': typeof TechJobsIndexRoute
  '/admin/elevators/$elevatorId/qr': typeof AdminElevatorsElevatorIdQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/contracts'
    | '/admin/leads'
    | '/admin/reports'
    | '/portal/contracts'
    | '/portal/issues'
    | '/qr/$elevatorId'
    | '/tech/route-plan'
    | '/tech/schedule'
    | '/admin/'
    | '/portal/'
    | '/tech/'
    | '/admin/customers/$customerId'
    | '/admin/elevators/$elevatorId'
    | '/admin/jobs/$jobId'
    | '/portal/elevators/$elevatorId'
    | '/tech/jobs/$jobId'
    | '/admin/customers/'
    | '/admin/elevators/'
    | '/admin/inventory/'
    | '/admin/jobs/'
    | '/portal/elevators/'
    | '/tech/jobs/'
    | '/admin/elevators/$elevatorId/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/contracts'
    | '/admin/leads'
    | '/admin/reports'
    | '/portal/contracts'
    | '/portal/issues'
    | '/qr/$elevatorId'
    | '/tech/route-plan'
    | '/tech/schedule'
    | '/admin'
    | '/portal'
    | '/tech'
    | '/admin/customers/$customerId'
    | '/admin/elevators/$elevatorId'
    | '/admin/jobs/$jobId'
    | '/portal/elevators/$elevatorId'
    | '/tech/jobs/$jobId'
    | '/admin/customers'
    | '/admin/elevators'
    | '/admin/inventory'
    | '/admin/jobs'
    | '/portal/elevators'
    | '/tech/jobs'
    | '/admin/elevators/$elevatorId/qr'
  id:
    | '__root__'
    | '/'
    | '/admin/contracts'
    | '/admin/leads'
    | '/admin/reports'
    | '/portal/contracts'
    | '/portal/issues'
    | '/qr/$elevatorId'
    | '/tech/route-plan'
    | '/tech/schedule'
    | '/admin/'
    | '/portal/'
    | '/tech/'
    | '/admin/customers/$customerId'
    | '/admin/elevators/$elevatorId'
    | '/admin/jobs/$jobId'
    | '/portal/elevators/$elevatorId'
    | '/tech/jobs/$jobId'
    | '/admin/customers/'
    | '/admin/elevators/'
    | '/admin/inventory/'
    | '/admin/jobs/'
    | '/portal/elevators/'
    | '/tech/jobs/'
    | '/admin/elevators/$elevatorId/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  PortalContractsRoute: typeof PortalContractsRoute
  PortalIssuesRoute: typeof PortalIssuesRoute
  QrElevatorIdRoute: typeof QrElevatorIdRoute
  TechRoutePlanRoute: typeof TechRoutePlanRoute
  TechScheduleRoute: typeof TechScheduleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  TechIndexRoute: typeof TechIndexRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminElevatorsElevatorIdRoute: typeof AdminElevatorsElevatorIdRouteWithChildren
  AdminJobsJobIdRoute: typeof AdminJobsJobIdRoute
  PortalElevatorsElevatorIdRoute: typeof PortalElevatorsElevatorIdRoute
  TechJobsJobIdRoute: typeof TechJobsJobIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminElevatorsIndexRoute: typeof AdminElevatorsIndexRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  PortalElevatorsIndexRoute: typeof PortalElevatorsIndexRoute
  TechJobsIndexRoute: typeof TechJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/': {
      id: '/tech/'
      path: '/tech'
      fullPath: '/tech/'
      preLoaderRoute: typeof TechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/schedule': {
      id: '/tech/schedule'
      path: '/tech/schedule'
      fullPath: '/tech/schedule'
      preLoaderRoute: typeof TechScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/route-plan': {
      id: '/tech/route-plan'
      path: '/tech/route-plan'
      fullPath: '/tech/route-plan'
      preLoaderRoute: typeof TechRoutePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$elevatorId': {
      id: '/qr/$elevatorId'
      path: '/qr/$elevatorId'
      fullPath: '/qr/$elevatorId'
      preLoaderRoute: typeof QrElevatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/issues': {
      id: '/portal/issues'
      path: '/portal/issues'
      fullPath: '/portal/issues'
      preLoaderRoute: typeof PortalIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/contracts': {
      id: '/portal/contracts'
      path: '/portal/contracts'
      fullPath: '/portal/contracts'
      preLoaderRoute: typeof PortalContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/admin/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/jobs/': {
      id: '/tech/jobs/'
      path: '/tech/jobs'
      fullPath: '/tech/jobs/'
      preLoaderRoute: typeof TechJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/elevators/': {
      id: '/portal/elevators/'
      path: '/portal/elevators'
      fullPath: '/portal/elevators/'
      preLoaderRoute: typeof PortalElevatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/admin/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/elevators/': {
      id: '/admin/elevators/'
      path: '/admin/elevators'
      fullPath: '/admin/elevators/'
      preLoaderRoute: typeof AdminElevatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/jobs/$jobId': {
      id: '/tech/jobs/$jobId'
      path: '/tech/jobs/$jobId'
      fullPath: '/tech/jobs/$jobId'
      preLoaderRoute: typeof TechJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/elevators/$elevatorId': {
      id: '/portal/elevators/$elevatorId'
      path: '/portal/elevators/$elevatorId'
      fullPath: '/portal/elevators/$elevatorId'
      preLoaderRoute: typeof PortalElevatorsElevatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/$jobId': {
      id: '/admin/jobs/$jobId'
      path: '/admin/jobs/$jobId'
      fullPath: '/admin/jobs/$jobId'
      preLoaderRoute: typeof AdminJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/elevators/$elevatorId': {
      id: '/admin/elevators/$elevatorId'
      path: '/admin/elevators/$elevatorId'
      fullPath: '/admin/elevators/$elevatorId'
      preLoaderRoute: typeof AdminElevatorsElevatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/admin/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/elevators/$elevatorId/qr': {
      id: '/admin/elevators/$elevatorId/qr'
      path: '/qr'
      fullPath: '/admin/elevators/$elevatorId/qr'
      preLoaderRoute: typeof AdminElevatorsElevatorIdQrRouteImport
      parentRoute: typeof AdminElevatorsElevatorIdRoute
    }
  }
}

interface AdminElevatorsElevatorIdRouteChildren {
  AdminElevatorsElevatorIdQrRoute: typeof AdminElevatorsElevatorIdQrRoute
}

const AdminElevatorsElevatorIdRouteChildren: AdminElevatorsElevatorIdRouteChildren =
  {
    AdminElevatorsElevatorIdQrRoute: AdminElevatorsElevatorIdQrRoute,
  }

const AdminElevatorsElevatorIdRouteWithChildren =
  AdminElevatorsElevatorIdRoute._addFileChildren(
    AdminElevatorsElevatorIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminReportsRoute: AdminReportsRoute,
  PortalContractsRoute: PortalContractsRoute,
  PortalIssuesRoute: PortalIssuesRoute,
  QrElevatorIdRoute: QrElevatorIdRoute,
  TechRoutePlanRoute: TechRoutePlanRoute,
  TechScheduleRoute: TechScheduleRoute,
  AdminIndexRoute: AdminIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  TechIndexRoute: TechIndexRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminElevatorsElevatorIdRoute: AdminElevatorsElevatorIdRouteWithChildren,
  AdminJobsJobIdRoute: AdminJobsJobIdRoute,
  PortalElevatorsElevatorIdRoute: PortalElevatorsElevatorIdRoute,
  TechJobsJobIdRoute: TechJobsJobIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminElevatorsIndexRoute: AdminElevatorsIndexRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  PortalElevatorsIndexRoute: PortalElevatorsIndexRoute,
  TechJobsIndexRoute: TechJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
