/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechIndexRouteImport } from './routes/tech.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as MobileIndexRouteImport } from './routes/mobile/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TechScheduleRouteImport } from './routes/tech.schedule'
import { Route as TechRoutePlanRouteImport } from './routes/tech.route-plan'
import { Route as QrElevatorIdRouteImport } from './routes/qr.$elevatorId'
import { Route as PortalIssuesRouteImport } from './routes/portal.issues'
import { Route as PortalContractsRouteImport } from './routes/portal.contracts'
import { Route as MobileSettingsRouteImport } from './routes/mobile/settings'
import { Route as MobileScheduleRouteImport } from './routes/mobile/schedule'
import { Route as MobileScannerRouteImport } from './routes/mobile/scanner'
import { Route as MobileRoutePlanRouteImport } from './routes/mobile/route-plan'
import { Route as MobileReportsRouteImport } from './routes/mobile/reports'
import { Route as MobileProjectsRouteImport } from './routes/mobile/projects'
import { Route as MobileProfileRouteImport } from './routes/mobile/profile'
import { Route as MobilePortalRouteImport } from './routes/mobile/portal'
import { Route as MobileLeadsRouteImport } from './routes/mobile/leads'
import { Route as MobileJobsRouteImport } from './routes/mobile/jobs'
import { Route as MobileInventoryRouteImport } from './routes/mobile/inventory'
import { Route as MobileHrRouteImport } from './routes/mobile/hr'
import { Route as MobileElevatorsRouteImport } from './routes/mobile/elevators'
import { Route as MobileCustomersRouteImport } from './routes/mobile/customers'
import { Route as MobileApprovalsRouteImport } from './routes/mobile/approvals'
import { Route as MobileAccountingRouteImport } from './routes/mobile/accounting'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminHrRouteImport } from './routes/admin.hr'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAccountingRouteImport } from './routes/admin.accounting'
import { Route as TechJobsIndexRouteImport } from './routes/tech.jobs.index'
import { Route as PortalElevatorsIndexRouteImport } from './routes/portal.elevators.index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin.jobs.index'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin.inventory.index'
import { Route as AdminElevatorsIndexRouteImport } from './routes/admin.elevators.index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as TechJobsJobIdRouteImport } from './routes/tech.jobs.$jobId'
import { Route as PortalElevatorsElevatorIdRouteImport } from './routes/portal.elevators.$elevatorId'
import { Route as MobileProjectsProjectIdRouteImport } from './routes/mobile/projects.$projectId'
import { Route as MobilePortalIssuesRouteImport } from './routes/mobile/portal.issues'
import { Route as MobileLeadsLeadIdRouteImport } from './routes/mobile/leads.$leadId'
import { Route as MobileJobsJobIdRouteImport } from './routes/mobile/jobs.$jobId'
import { Route as MobileInventoryItemIdRouteImport } from './routes/mobile/inventory.$itemId'
import { Route as MobileElevatorsElevatorIdRouteImport } from './routes/mobile/elevators.$elevatorId'
import { Route as MobileCustomersCustomerIdRouteImport } from './routes/mobile/customers.$customerId'
import { Route as MobileContractsContractIdRouteImport } from './routes/mobile/contracts.$contractId'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin.projects.$projectId'
import { Route as AdminJobsJobIdRouteImport } from './routes/admin.jobs.$jobId'
import { Route as AdminElevatorsElevatorIdRouteImport } from './routes/admin.elevators.$elevatorId'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'
import { Route as AdminElevatorsElevatorIdQrRouteImport } from './routes/admin.elevators.$elevatorId.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechIndexRoute = TechIndexRouteImport.update({
  id: '/tech/',
  path: '/tech/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/mobile/',
  path: '/mobile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechScheduleRoute = TechScheduleRouteImport.update({
  id: '/tech/schedule',
  path: '/tech/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRoutePlanRoute = TechRoutePlanRouteImport.update({
  id: '/tech/route-plan',
  path: '/tech/route-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const QrElevatorIdRoute = QrElevatorIdRouteImport.update({
  id: '/qr/$elevatorId',
  path: '/qr/$elevatorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIssuesRoute = PortalIssuesRouteImport.update({
  id: '/portal/issues',
  path: '/portal/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalContractsRoute = PortalContractsRouteImport.update({
  id: '/portal/contracts',
  path: '/portal/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileSettingsRoute = MobileSettingsRouteImport.update({
  id: '/mobile/settings',
  path: '/mobile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileScheduleRoute = MobileScheduleRouteImport.update({
  id: '/mobile/schedule',
  path: '/mobile/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileScannerRoute = MobileScannerRouteImport.update({
  id: '/mobile/scanner',
  path: '/mobile/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoutePlanRoute = MobileRoutePlanRouteImport.update({
  id: '/mobile/route-plan',
  path: '/mobile/route-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileReportsRoute = MobileReportsRouteImport.update({
  id: '/mobile/reports',
  path: '/mobile/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileProjectsRoute = MobileProjectsRouteImport.update({
  id: '/mobile/projects',
  path: '/mobile/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileProfileRoute = MobileProfileRouteImport.update({
  id: '/mobile/profile',
  path: '/mobile/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilePortalRoute = MobilePortalRouteImport.update({
  id: '/mobile/portal',
  path: '/mobile/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileLeadsRoute = MobileLeadsRouteImport.update({
  id: '/mobile/leads',
  path: '/mobile/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileJobsRoute = MobileJobsRouteImport.update({
  id: '/mobile/jobs',
  path: '/mobile/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileInventoryRoute = MobileInventoryRouteImport.update({
  id: '/mobile/inventory',
  path: '/mobile/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileHrRoute = MobileHrRouteImport.update({
  id: '/mobile/hr',
  path: '/mobile/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileElevatorsRoute = MobileElevatorsRouteImport.update({
  id: '/mobile/elevators',
  path: '/mobile/elevators',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileCustomersRoute = MobileCustomersRouteImport.update({
  id: '/mobile/customers',
  path: '/mobile/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileApprovalsRoute = MobileApprovalsRouteImport.update({
  id: '/mobile/approvals',
  path: '/mobile/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAccountingRoute = MobileAccountingRouteImport.update({
  id: '/mobile/accounting',
  path: '/mobile/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHrRoute = AdminHrRouteImport.update({
  id: '/admin/hr',
  path: '/admin/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/admin/contracts',
  path: '/admin/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountingRoute = AdminAccountingRouteImport.update({
  id: '/admin/accounting',
  path: '/admin/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const TechJobsIndexRoute = TechJobsIndexRouteImport.update({
  id: '/tech/jobs/',
  path: '/tech/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalElevatorsIndexRoute = PortalElevatorsIndexRouteImport.update({
  id: '/portal/elevators/',
  path: '/portal/elevators/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/admin/jobs/',
  path: '/admin/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/admin/inventory/',
  path: '/admin/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminElevatorsIndexRoute = AdminElevatorsIndexRouteImport.update({
  id: '/admin/elevators/',
  path: '/admin/elevators/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/admin/customers/',
  path: '/admin/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechJobsJobIdRoute = TechJobsJobIdRouteImport.update({
  id: '/tech/jobs/$jobId',
  path: '/tech/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalElevatorsElevatorIdRoute =
  PortalElevatorsElevatorIdRouteImport.update({
    id: '/portal/elevators/$elevatorId',
    path: '/portal/elevators/$elevatorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MobileProjectsProjectIdRoute = MobileProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => MobileProjectsRoute,
} as any)
const MobilePortalIssuesRoute = MobilePortalIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => MobilePortalRoute,
} as any)
const MobileLeadsLeadIdRoute = MobileLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => MobileLeadsRoute,
} as any)
const MobileJobsJobIdRoute = MobileJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => MobileJobsRoute,
} as any)
const MobileInventoryItemIdRoute = MobileInventoryItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => MobileInventoryRoute,
} as any)
const MobileElevatorsElevatorIdRoute =
  MobileElevatorsElevatorIdRouteImport.update({
    id: '/$elevatorId',
    path: '/$elevatorId',
    getParentRoute: () => MobileElevatorsRoute,
  } as any)
const MobileCustomersCustomerIdRoute =
  MobileCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => MobileCustomersRoute,
  } as any)
const MobileContractsContractIdRoute =
  MobileContractsContractIdRouteImport.update({
    id: '/mobile/contracts/$contractId',
    path: '/mobile/contracts/$contractId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/admin/projects/$projectId',
  path: '/admin/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsJobIdRoute = AdminJobsJobIdRouteImport.update({
  id: '/admin/jobs/$jobId',
  path: '/admin/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminElevatorsElevatorIdRoute =
  AdminElevatorsElevatorIdRouteImport.update({
    id: '/admin/elevators/$elevatorId',
    path: '/admin/elevators/$elevatorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/admin/customers/$customerId',
    path: '/admin/customers/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminElevatorsElevatorIdQrRoute =
  AdminElevatorsElevatorIdQrRouteImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AdminElevatorsElevatorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/mobile/accounting': typeof MobileAccountingRoute
  '/mobile/approvals': typeof MobileApprovalsRoute
  '/mobile/customers': typeof MobileCustomersRouteWithChildren
  '/mobile/elevators': typeof MobileElevatorsRouteWithChildren
  '/mobile/hr': typeof MobileHrRoute
  '/mobile/inventory': typeof MobileInventoryRouteWithChildren
  '/mobile/jobs': typeof MobileJobsRouteWithChildren
  '/mobile/leads': typeof MobileLeadsRouteWithChildren
  '/mobile/portal': typeof MobilePortalRouteWithChildren
  '/mobile/profile': typeof MobileProfileRoute
  '/mobile/projects': typeof MobileProjectsRouteWithChildren
  '/mobile/reports': typeof MobileReportsRoute
  '/mobile/route-plan': typeof MobileRoutePlanRoute
  '/mobile/scanner': typeof MobileScannerRoute
  '/mobile/schedule': typeof MobileScheduleRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/issues': typeof PortalIssuesRoute
  '/qr/$elevatorId': typeof QrElevatorIdRoute
  '/tech/route-plan': typeof TechRoutePlanRoute
  '/tech/schedule': typeof TechScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/tech/': typeof TechIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/elevators/$elevatorId': typeof AdminElevatorsElevatorIdRouteWithChildren
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/mobile/contracts/$contractId': typeof MobileContractsContractIdRoute
  '/mobile/customers/$customerId': typeof MobileCustomersCustomerIdRoute
  '/mobile/elevators/$elevatorId': typeof MobileElevatorsElevatorIdRoute
  '/mobile/inventory/$itemId': typeof MobileInventoryItemIdRoute
  '/mobile/jobs/$jobId': typeof MobileJobsJobIdRoute
  '/mobile/leads/$leadId': typeof MobileLeadsLeadIdRoute
  '/mobile/portal/issues': typeof MobilePortalIssuesRoute
  '/mobile/projects/$projectId': typeof MobileProjectsProjectIdRoute
  '/portal/elevators/$elevatorId': typeof PortalElevatorsElevatorIdRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/elevators/': typeof AdminElevatorsIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/portal/elevators/': typeof PortalElevatorsIndexRoute
  '/tech/jobs/': typeof TechJobsIndexRoute
  '/admin/elevators/$elevatorId/qr': typeof AdminElevatorsElevatorIdQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/mobile/accounting': typeof MobileAccountingRoute
  '/mobile/approvals': typeof MobileApprovalsRoute
  '/mobile/customers': typeof MobileCustomersRouteWithChildren
  '/mobile/elevators': typeof MobileElevatorsRouteWithChildren
  '/mobile/hr': typeof MobileHrRoute
  '/mobile/inventory': typeof MobileInventoryRouteWithChildren
  '/mobile/jobs': typeof MobileJobsRouteWithChildren
  '/mobile/leads': typeof MobileLeadsRouteWithChildren
  '/mobile/portal': typeof MobilePortalRouteWithChildren
  '/mobile/profile': typeof MobileProfileRoute
  '/mobile/projects': typeof MobileProjectsRouteWithChildren
  '/mobile/reports': typeof MobileReportsRoute
  '/mobile/route-plan': typeof MobileRoutePlanRoute
  '/mobile/scanner': typeof MobileScannerRoute
  '/mobile/schedule': typeof MobileScheduleRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/issues': typeof PortalIssuesRoute
  '/qr/$elevatorId': typeof QrElevatorIdRoute
  '/tech/route-plan': typeof TechRoutePlanRoute
  '/tech/schedule': typeof TechScheduleRoute
  '/admin': typeof AdminIndexRoute
  '/mobile': typeof MobileIndexRoute
  '/portal': typeof PortalIndexRoute
  '/tech': typeof TechIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/elevators/$elevatorId': typeof AdminElevatorsElevatorIdRouteWithChildren
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/mobile/contracts/$contractId': typeof MobileContractsContractIdRoute
  '/mobile/customers/$customerId': typeof MobileCustomersCustomerIdRoute
  '/mobile/elevators/$elevatorId': typeof MobileElevatorsElevatorIdRoute
  '/mobile/inventory/$itemId': typeof MobileInventoryItemIdRoute
  '/mobile/jobs/$jobId': typeof MobileJobsJobIdRoute
  '/mobile/leads/$leadId': typeof MobileLeadsLeadIdRoute
  '/mobile/portal/issues': typeof MobilePortalIssuesRoute
  '/mobile/projects/$projectId': typeof MobileProjectsProjectIdRoute
  '/portal/elevators/$elevatorId': typeof PortalElevatorsElevatorIdRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/elevators': typeof AdminElevatorsIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/portal/elevators': typeof PortalElevatorsIndexRoute
  '/tech/jobs': typeof TechJobsIndexRoute
  '/admin/elevators/$elevatorId/qr': typeof AdminElevatorsElevatorIdQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/mobile/accounting': typeof MobileAccountingRoute
  '/mobile/approvals': typeof MobileApprovalsRoute
  '/mobile/customers': typeof MobileCustomersRouteWithChildren
  '/mobile/elevators': typeof MobileElevatorsRouteWithChildren
  '/mobile/hr': typeof MobileHrRoute
  '/mobile/inventory': typeof MobileInventoryRouteWithChildren
  '/mobile/jobs': typeof MobileJobsRouteWithChildren
  '/mobile/leads': typeof MobileLeadsRouteWithChildren
  '/mobile/portal': typeof MobilePortalRouteWithChildren
  '/mobile/profile': typeof MobileProfileRoute
  '/mobile/projects': typeof MobileProjectsRouteWithChildren
  '/mobile/reports': typeof MobileReportsRoute
  '/mobile/route-plan': typeof MobileRoutePlanRoute
  '/mobile/scanner': typeof MobileScannerRoute
  '/mobile/schedule': typeof MobileScheduleRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/portal/issues': typeof PortalIssuesRoute
  '/qr/$elevatorId': typeof QrElevatorIdRoute
  '/tech/route-plan': typeof TechRoutePlanRoute
  '/tech/schedule': typeof TechScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/tech/': typeof TechIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/elevators/$elevatorId': typeof AdminElevatorsElevatorIdRouteWithChildren
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/mobile/contracts/$contractId': typeof MobileContractsContractIdRoute
  '/mobile/customers/$customerId': typeof MobileCustomersCustomerIdRoute
  '/mobile/elevators/$elevatorId': typeof MobileElevatorsElevatorIdRoute
  '/mobile/inventory/$itemId': typeof MobileInventoryItemIdRoute
  '/mobile/jobs/$jobId': typeof MobileJobsJobIdRoute
  '/mobile/leads/$leadId': typeof MobileLeadsLeadIdRoute
  '/mobile/portal/issues': typeof MobilePortalIssuesRoute
  '/mobile/projects/$projectId': typeof MobileProjectsProjectIdRoute
  '/portal/elevators/$elevatorId': typeof PortalElevatorsElevatorIdRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/elevators/': typeof AdminElevatorsIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/portal/elevators/': typeof PortalElevatorsIndexRoute
  '/tech/jobs/': typeof TechJobsIndexRoute
  '/admin/elevators/$elevatorId/qr': typeof AdminElevatorsElevatorIdQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/accounting'
    | '/admin/approvals'
    | '/admin/contracts'
    | '/admin/hr'
    | '/admin/leads'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/mobile/accounting'
    | '/mobile/approvals'
    | '/mobile/customers'
    | '/mobile/elevators'
    | '/mobile/hr'
    | '/mobile/inventory'
    | '/mobile/jobs'
    | '/mobile/leads'
    | '/mobile/portal'
    | '/mobile/profile'
    | '/mobile/projects'
    | '/mobile/reports'
    | '/mobile/route-plan'
    | '/mobile/scanner'
    | '/mobile/schedule'
    | '/mobile/settings'
    | '/portal/contracts'
    | '/portal/issues'
    | '/qr/$elevatorId'
    | '/tech/route-plan'
    | '/tech/schedule'
    | '/admin/'
    | '/mobile/'
    | '/portal/'
    | '/tech/'
    | '/admin/customers/$customerId'
    | '/admin/elevators/$elevatorId'
    | '/admin/jobs/$jobId'
    | '/admin/projects/$projectId'
    | '/mobile/contracts/$contractId'
    | '/mobile/customers/$customerId'
    | '/mobile/elevators/$elevatorId'
    | '/mobile/inventory/$itemId'
    | '/mobile/jobs/$jobId'
    | '/mobile/leads/$leadId'
    | '/mobile/portal/issues'
    | '/mobile/projects/$projectId'
    | '/portal/elevators/$elevatorId'
    | '/tech/jobs/$jobId'
    | '/admin/customers/'
    | '/admin/elevators/'
    | '/admin/inventory/'
    | '/admin/jobs/'
    | '/admin/projects/'
    | '/portal/elevators/'
    | '/tech/jobs/'
    | '/admin/elevators/$elevatorId/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/accounting'
    | '/admin/approvals'
    | '/admin/contracts'
    | '/admin/hr'
    | '/admin/leads'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/mobile/accounting'
    | '/mobile/approvals'
    | '/mobile/customers'
    | '/mobile/elevators'
    | '/mobile/hr'
    | '/mobile/inventory'
    | '/mobile/jobs'
    | '/mobile/leads'
    | '/mobile/portal'
    | '/mobile/profile'
    | '/mobile/projects'
    | '/mobile/reports'
    | '/mobile/route-plan'
    | '/mobile/scanner'
    | '/mobile/schedule'
    | '/mobile/settings'
    | '/portal/contracts'
    | '/portal/issues'
    | '/qr/$elevatorId'
    | '/tech/route-plan'
    | '/tech/schedule'
    | '/admin'
    | '/mobile'
    | '/portal'
    | '/tech'
    | '/admin/customers/$customerId'
    | '/admin/elevators/$elevatorId'
    | '/admin/jobs/$jobId'
    | '/admin/projects/$projectId'
    | '/mobile/contracts/$contractId'
    | '/mobile/customers/$customerId'
    | '/mobile/elevators/$elevatorId'
    | '/mobile/inventory/$itemId'
    | '/mobile/jobs/$jobId'
    | '/mobile/leads/$leadId'
    | '/mobile/portal/issues'
    | '/mobile/projects/$projectId'
    | '/portal/elevators/$elevatorId'
    | '/tech/jobs/$jobId'
    | '/admin/customers'
    | '/admin/elevators'
    | '/admin/inventory'
    | '/admin/jobs'
    | '/admin/projects'
    | '/portal/elevators'
    | '/tech/jobs'
    | '/admin/elevators/$elevatorId/qr'
  id:
    | '__root__'
    | '/'
    | '/admin/accounting'
    | '/admin/approvals'
    | '/admin/contracts'
    | '/admin/hr'
    | '/admin/leads'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/mobile/accounting'
    | '/mobile/approvals'
    | '/mobile/customers'
    | '/mobile/elevators'
    | '/mobile/hr'
    | '/mobile/inventory'
    | '/mobile/jobs'
    | '/mobile/leads'
    | '/mobile/portal'
    | '/mobile/profile'
    | '/mobile/projects'
    | '/mobile/reports'
    | '/mobile/route-plan'
    | '/mobile/scanner'
    | '/mobile/schedule'
    | '/mobile/settings'
    | '/portal/contracts'
    | '/portal/issues'
    | '/qr/$elevatorId'
    | '/tech/route-plan'
    | '/tech/schedule'
    | '/admin/'
    | '/mobile/'
    | '/portal/'
    | '/tech/'
    | '/admin/customers/$customerId'
    | '/admin/elevators/$elevatorId'
    | '/admin/jobs/$jobId'
    | '/admin/projects/$projectId'
    | '/mobile/contracts/$contractId'
    | '/mobile/customers/$customerId'
    | '/mobile/elevators/$elevatorId'
    | '/mobile/inventory/$itemId'
    | '/mobile/jobs/$jobId'
    | '/mobile/leads/$leadId'
    | '/mobile/portal/issues'
    | '/mobile/projects/$projectId'
    | '/portal/elevators/$elevatorId'
    | '/tech/jobs/$jobId'
    | '/admin/customers/'
    | '/admin/elevators/'
    | '/admin/inventory/'
    | '/admin/jobs/'
    | '/admin/projects/'
    | '/portal/elevators/'
    | '/tech/jobs/'
    | '/admin/elevators/$elevatorId/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAccountingRoute: typeof AdminAccountingRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminHrRoute: typeof AdminHrRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  MobileAccountingRoute: typeof MobileAccountingRoute
  MobileApprovalsRoute: typeof MobileApprovalsRoute
  MobileCustomersRoute: typeof MobileCustomersRouteWithChildren
  MobileElevatorsRoute: typeof MobileElevatorsRouteWithChildren
  MobileHrRoute: typeof MobileHrRoute
  MobileInventoryRoute: typeof MobileInventoryRouteWithChildren
  MobileJobsRoute: typeof MobileJobsRouteWithChildren
  MobileLeadsRoute: typeof MobileLeadsRouteWithChildren
  MobilePortalRoute: typeof MobilePortalRouteWithChildren
  MobileProfileRoute: typeof MobileProfileRoute
  MobileProjectsRoute: typeof MobileProjectsRouteWithChildren
  MobileReportsRoute: typeof MobileReportsRoute
  MobileRoutePlanRoute: typeof MobileRoutePlanRoute
  MobileScannerRoute: typeof MobileScannerRoute
  MobileScheduleRoute: typeof MobileScheduleRoute
  MobileSettingsRoute: typeof MobileSettingsRoute
  PortalContractsRoute: typeof PortalContractsRoute
  PortalIssuesRoute: typeof PortalIssuesRoute
  QrElevatorIdRoute: typeof QrElevatorIdRoute
  TechRoutePlanRoute: typeof TechRoutePlanRoute
  TechScheduleRoute: typeof TechScheduleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MobileIndexRoute: typeof MobileIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  TechIndexRoute: typeof TechIndexRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminElevatorsElevatorIdRoute: typeof AdminElevatorsElevatorIdRouteWithChildren
  AdminJobsJobIdRoute: typeof AdminJobsJobIdRoute
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRoute
  MobileContractsContractIdRoute: typeof MobileContractsContractIdRoute
  PortalElevatorsElevatorIdRoute: typeof PortalElevatorsElevatorIdRoute
  TechJobsJobIdRoute: typeof TechJobsJobIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminElevatorsIndexRoute: typeof AdminElevatorsIndexRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  PortalElevatorsIndexRoute: typeof PortalElevatorsIndexRoute
  TechJobsIndexRoute: typeof TechJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/': {
      id: '/tech/'
      path: '/tech'
      fullPath: '/tech/'
      preLoaderRoute: typeof TechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/mobile'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/schedule': {
      id: '/tech/schedule'
      path: '/tech/schedule'
      fullPath: '/tech/schedule'
      preLoaderRoute: typeof TechScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/route-plan': {
      id: '/tech/route-plan'
      path: '/tech/route-plan'
      fullPath: '/tech/route-plan'
      preLoaderRoute: typeof TechRoutePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$elevatorId': {
      id: '/qr/$elevatorId'
      path: '/qr/$elevatorId'
      fullPath: '/qr/$elevatorId'
      preLoaderRoute: typeof QrElevatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/issues': {
      id: '/portal/issues'
      path: '/portal/issues'
      fullPath: '/portal/issues'
      preLoaderRoute: typeof PortalIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/contracts': {
      id: '/portal/contracts'
      path: '/portal/contracts'
      fullPath: '/portal/contracts'
      preLoaderRoute: typeof PortalContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/settings': {
      id: '/mobile/settings'
      path: '/mobile/settings'
      fullPath: '/mobile/settings'
      preLoaderRoute: typeof MobileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/schedule': {
      id: '/mobile/schedule'
      path: '/mobile/schedule'
      fullPath: '/mobile/schedule'
      preLoaderRoute: typeof MobileScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/scanner': {
      id: '/mobile/scanner'
      path: '/mobile/scanner'
      fullPath: '/mobile/scanner'
      preLoaderRoute: typeof MobileScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/route-plan': {
      id: '/mobile/route-plan'
      path: '/mobile/route-plan'
      fullPath: '/mobile/route-plan'
      preLoaderRoute: typeof MobileRoutePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/reports': {
      id: '/mobile/reports'
      path: '/mobile/reports'
      fullPath: '/mobile/reports'
      preLoaderRoute: typeof MobileReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/projects': {
      id: '/mobile/projects'
      path: '/mobile/projects'
      fullPath: '/mobile/projects'
      preLoaderRoute: typeof MobileProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/profile': {
      id: '/mobile/profile'
      path: '/mobile/profile'
      fullPath: '/mobile/profile'
      preLoaderRoute: typeof MobileProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/portal': {
      id: '/mobile/portal'
      path: '/mobile/portal'
      fullPath: '/mobile/portal'
      preLoaderRoute: typeof MobilePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/leads': {
      id: '/mobile/leads'
      path: '/mobile/leads'
      fullPath: '/mobile/leads'
      preLoaderRoute: typeof MobileLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/jobs': {
      id: '/mobile/jobs'
      path: '/mobile/jobs'
      fullPath: '/mobile/jobs'
      preLoaderRoute: typeof MobileJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/inventory': {
      id: '/mobile/inventory'
      path: '/mobile/inventory'
      fullPath: '/mobile/inventory'
      preLoaderRoute: typeof MobileInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/hr': {
      id: '/mobile/hr'
      path: '/mobile/hr'
      fullPath: '/mobile/hr'
      preLoaderRoute: typeof MobileHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/elevators': {
      id: '/mobile/elevators'
      path: '/mobile/elevators'
      fullPath: '/mobile/elevators'
      preLoaderRoute: typeof MobileElevatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/customers': {
      id: '/mobile/customers'
      path: '/mobile/customers'
      fullPath: '/mobile/customers'
      preLoaderRoute: typeof MobileCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/approvals': {
      id: '/mobile/approvals'
      path: '/mobile/approvals'
      fullPath: '/mobile/approvals'
      preLoaderRoute: typeof MobileApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/accounting': {
      id: '/mobile/accounting'
      path: '/mobile/accounting'
      fullPath: '/mobile/accounting'
      preLoaderRoute: typeof MobileAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hr': {
      id: '/admin/hr'
      path: '/admin/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AdminHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/admin/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounting': {
      id: '/admin/accounting'
      path: '/admin/accounting'
      fullPath: '/admin/accounting'
      preLoaderRoute: typeof AdminAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/jobs/': {
      id: '/tech/jobs/'
      path: '/tech/jobs'
      fullPath: '/tech/jobs/'
      preLoaderRoute: typeof TechJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/elevators/': {
      id: '/portal/elevators/'
      path: '/portal/elevators'
      fullPath: '/portal/elevators/'
      preLoaderRoute: typeof PortalElevatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/admin/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/elevators/': {
      id: '/admin/elevators/'
      path: '/admin/elevators'
      fullPath: '/admin/elevators/'
      preLoaderRoute: typeof AdminElevatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/jobs/$jobId': {
      id: '/tech/jobs/$jobId'
      path: '/tech/jobs/$jobId'
      fullPath: '/tech/jobs/$jobId'
      preLoaderRoute: typeof TechJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/elevators/$elevatorId': {
      id: '/portal/elevators/$elevatorId'
      path: '/portal/elevators/$elevatorId'
      fullPath: '/portal/elevators/$elevatorId'
      preLoaderRoute: typeof PortalElevatorsElevatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/projects/$projectId': {
      id: '/mobile/projects/$projectId'
      path: '/$projectId'
      fullPath: '/mobile/projects/$projectId'
      preLoaderRoute: typeof MobileProjectsProjectIdRouteImport
      parentRoute: typeof MobileProjectsRoute
    }
    '/mobile/portal/issues': {
      id: '/mobile/portal/issues'
      path: '/issues'
      fullPath: '/mobile/portal/issues'
      preLoaderRoute: typeof MobilePortalIssuesRouteImport
      parentRoute: typeof MobilePortalRoute
    }
    '/mobile/leads/$leadId': {
      id: '/mobile/leads/$leadId'
      path: '/$leadId'
      fullPath: '/mobile/leads/$leadId'
      preLoaderRoute: typeof MobileLeadsLeadIdRouteImport
      parentRoute: typeof MobileLeadsRoute
    }
    '/mobile/jobs/$jobId': {
      id: '/mobile/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/mobile/jobs/$jobId'
      preLoaderRoute: typeof MobileJobsJobIdRouteImport
      parentRoute: typeof MobileJobsRoute
    }
    '/mobile/inventory/$itemId': {
      id: '/mobile/inventory/$itemId'
      path: '/$itemId'
      fullPath: '/mobile/inventory/$itemId'
      preLoaderRoute: typeof MobileInventoryItemIdRouteImport
      parentRoute: typeof MobileInventoryRoute
    }
    '/mobile/elevators/$elevatorId': {
      id: '/mobile/elevators/$elevatorId'
      path: '/$elevatorId'
      fullPath: '/mobile/elevators/$elevatorId'
      preLoaderRoute: typeof MobileElevatorsElevatorIdRouteImport
      parentRoute: typeof MobileElevatorsRoute
    }
    '/mobile/customers/$customerId': {
      id: '/mobile/customers/$customerId'
      path: '/$customerId'
      fullPath: '/mobile/customers/$customerId'
      preLoaderRoute: typeof MobileCustomersCustomerIdRouteImport
      parentRoute: typeof MobileCustomersRoute
    }
    '/mobile/contracts/$contractId': {
      id: '/mobile/contracts/$contractId'
      path: '/mobile/contracts/$contractId'
      fullPath: '/mobile/contracts/$contractId'
      preLoaderRoute: typeof MobileContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/admin/projects/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/$jobId': {
      id: '/admin/jobs/$jobId'
      path: '/admin/jobs/$jobId'
      fullPath: '/admin/jobs/$jobId'
      preLoaderRoute: typeof AdminJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/elevators/$elevatorId': {
      id: '/admin/elevators/$elevatorId'
      path: '/admin/elevators/$elevatorId'
      fullPath: '/admin/elevators/$elevatorId'
      preLoaderRoute: typeof AdminElevatorsElevatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/admin/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/elevators/$elevatorId/qr': {
      id: '/admin/elevators/$elevatorId/qr'
      path: '/qr'
      fullPath: '/admin/elevators/$elevatorId/qr'
      preLoaderRoute: typeof AdminElevatorsElevatorIdQrRouteImport
      parentRoute: typeof AdminElevatorsElevatorIdRoute
    }
  }
}

interface MobileCustomersRouteChildren {
  MobileCustomersCustomerIdRoute: typeof MobileCustomersCustomerIdRoute
}

const MobileCustomersRouteChildren: MobileCustomersRouteChildren = {
  MobileCustomersCustomerIdRoute: MobileCustomersCustomerIdRoute,
}

const MobileCustomersRouteWithChildren = MobileCustomersRoute._addFileChildren(
  MobileCustomersRouteChildren,
)

interface MobileElevatorsRouteChildren {
  MobileElevatorsElevatorIdRoute: typeof MobileElevatorsElevatorIdRoute
}

const MobileElevatorsRouteChildren: MobileElevatorsRouteChildren = {
  MobileElevatorsElevatorIdRoute: MobileElevatorsElevatorIdRoute,
}

const MobileElevatorsRouteWithChildren = MobileElevatorsRoute._addFileChildren(
  MobileElevatorsRouteChildren,
)

interface MobileInventoryRouteChildren {
  MobileInventoryItemIdRoute: typeof MobileInventoryItemIdRoute
}

const MobileInventoryRouteChildren: MobileInventoryRouteChildren = {
  MobileInventoryItemIdRoute: MobileInventoryItemIdRoute,
}

const MobileInventoryRouteWithChildren = MobileInventoryRoute._addFileChildren(
  MobileInventoryRouteChildren,
)

interface MobileJobsRouteChildren {
  MobileJobsJobIdRoute: typeof MobileJobsJobIdRoute
}

const MobileJobsRouteChildren: MobileJobsRouteChildren = {
  MobileJobsJobIdRoute: MobileJobsJobIdRoute,
}

const MobileJobsRouteWithChildren = MobileJobsRoute._addFileChildren(
  MobileJobsRouteChildren,
)

interface MobileLeadsRouteChildren {
  MobileLeadsLeadIdRoute: typeof MobileLeadsLeadIdRoute
}

const MobileLeadsRouteChildren: MobileLeadsRouteChildren = {
  MobileLeadsLeadIdRoute: MobileLeadsLeadIdRoute,
}

const MobileLeadsRouteWithChildren = MobileLeadsRoute._addFileChildren(
  MobileLeadsRouteChildren,
)

interface MobilePortalRouteChildren {
  MobilePortalIssuesRoute: typeof MobilePortalIssuesRoute
}

const MobilePortalRouteChildren: MobilePortalRouteChildren = {
  MobilePortalIssuesRoute: MobilePortalIssuesRoute,
}

const MobilePortalRouteWithChildren = MobilePortalRoute._addFileChildren(
  MobilePortalRouteChildren,
)

interface MobileProjectsRouteChildren {
  MobileProjectsProjectIdRoute: typeof MobileProjectsProjectIdRoute
}

const MobileProjectsRouteChildren: MobileProjectsRouteChildren = {
  MobileProjectsProjectIdRoute: MobileProjectsProjectIdRoute,
}

const MobileProjectsRouteWithChildren = MobileProjectsRoute._addFileChildren(
  MobileProjectsRouteChildren,
)

interface AdminElevatorsElevatorIdRouteChildren {
  AdminElevatorsElevatorIdQrRoute: typeof AdminElevatorsElevatorIdQrRoute
}

const AdminElevatorsElevatorIdRouteChildren: AdminElevatorsElevatorIdRouteChildren =
  {
    AdminElevatorsElevatorIdQrRoute: AdminElevatorsElevatorIdQrRoute,
  }

const AdminElevatorsElevatorIdRouteWithChildren =
  AdminElevatorsElevatorIdRoute._addFileChildren(
    AdminElevatorsElevatorIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAccountingRoute: AdminAccountingRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminHrRoute: AdminHrRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  MobileAccountingRoute: MobileAccountingRoute,
  MobileApprovalsRoute: MobileApprovalsRoute,
  MobileCustomersRoute: MobileCustomersRouteWithChildren,
  MobileElevatorsRoute: MobileElevatorsRouteWithChildren,
  MobileHrRoute: MobileHrRoute,
  MobileInventoryRoute: MobileInventoryRouteWithChildren,
  MobileJobsRoute: MobileJobsRouteWithChildren,
  MobileLeadsRoute: MobileLeadsRouteWithChildren,
  MobilePortalRoute: MobilePortalRouteWithChildren,
  MobileProfileRoute: MobileProfileRoute,
  MobileProjectsRoute: MobileProjectsRouteWithChildren,
  MobileReportsRoute: MobileReportsRoute,
  MobileRoutePlanRoute: MobileRoutePlanRoute,
  MobileScannerRoute: MobileScannerRoute,
  MobileScheduleRoute: MobileScheduleRoute,
  MobileSettingsRoute: MobileSettingsRoute,
  PortalContractsRoute: PortalContractsRoute,
  PortalIssuesRoute: PortalIssuesRoute,
  QrElevatorIdRoute: QrElevatorIdRoute,
  TechRoutePlanRoute: TechRoutePlanRoute,
  TechScheduleRoute: TechScheduleRoute,
  AdminIndexRoute: AdminIndexRoute,
  MobileIndexRoute: MobileIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  TechIndexRoute: TechIndexRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminElevatorsElevatorIdRoute: AdminElevatorsElevatorIdRouteWithChildren,
  AdminJobsJobIdRoute: AdminJobsJobIdRoute,
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRoute,
  MobileContractsContractIdRoute: MobileContractsContractIdRoute,
  PortalElevatorsElevatorIdRoute: PortalElevatorsElevatorIdRoute,
  TechJobsJobIdRoute: TechJobsJobIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminElevatorsIndexRoute: AdminElevatorsIndexRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  PortalElevatorsIndexRoute: PortalElevatorsIndexRoute,
  TechJobsIndexRoute: TechJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
